// <auto-generated />
using APARTMENT_API.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace APARTMENT_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629020133_CreateFloorTable")]
    partial class CreateFloorTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APARTMENT_API.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2")
                        .HasColumnName("NameEnglish");

                    b.Property<string>("NameKhmer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar2")
                        .HasColumnName("NameKhmer");

                    b.HasKey("Id");

                    b.ToTable("TblBuilding");
                });

            modelBuilder.Entity("APARTMENT_API.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuildingId")
                        .HasColumnType("number")
                        .HasColumnName("BuildingId");

                    b.Property<byte>("FloorNo")
                        .HasColumnType("number(3)")
                        .HasColumnName("FloorNo");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("TblFloor");
                });

            modelBuilder.Entity("APARTMENT_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("number(1)")
                        .HasColumnName("Active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar2(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("TblUser");
                });

            modelBuilder.Entity("APARTMENT_API.Models.Floor", b =>
                {
                    b.HasOne("APARTMENT_API.Models.Building", "building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("building");
                });
#pragma warning restore 612, 618
        }
    }
}
