using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace APARTMENT_API.Migrations
{
    /// <inheritdoc />
    public partial class creatTblGuest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if table exists before creating (idempotent migration)
            migrationBuilder.Sql(@"
                DECLARE
                    V_COUNT INTEGER;
                BEGIN
                    SELECT COUNT(*) INTO V_COUNT FROM user_tables WHERE table_name = 'TblGuest';
                    IF V_COUNT = 0 THEN
                        EXECUTE IMMEDIATE 'CREATE TABLE TblGuest (
                            Id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                            NameEnglish varchar2(50),
                            NameKhmer nvarchar2(50),
                            Sex varchar2(10),
                            DOB DATE,
                            Address nvarchar2(100),
                            Nationality varchar2(50),
                            Phone varchar2(50),
                            Email varchar2(20),
                            SSN varchar2(20),
                            Passport varchar2(20),
                            Status varchar2(20),
                            Image Varchar2(200),
                            CONSTRAINT PK_TblGuest PRIMARY KEY (Id)
                        )';
                    END IF;
                END;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TblGuest");
        }
    }
}